export const employees = [
    {
        id: 1,
        employeeName: "Tony Reichert",
        designation: "CEO",
        email: "tony.reichert@example.com",
        dob: "29/02/1990",
        department: "Manager",
        team: "Management",
        status: "active",
        mobile: "+255-655-788-788",
        birthPlace: "Shinyanga",
        joiningDate: "29/02/2020",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    },
    {
        id: 2,
        employeeName: "Zoey Lang",
        designation: "Tech Lead",
        email: "zoey.lang@example.com",
        dob: "09/02/1989",
        department: "Manager",
        team: "Development",
        status: "paused",
        mobile: "+255 655 000 000",
        birthPlace: "Varginia",
        joiningDate: "29/02/2020",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    },
    {
        id: 3,
        employeeName: "Jane Fisher",
        designation: "CEO",
        email: "tony.reichert@example.com",
        dob: "29/02/1990",
        department: "Manager",
        team: "Management",
        status: "active",
        mobile: "+255 655 788 788",
        birthPlace: "Shinyanga",
        joiningDate: "29/02/2020",
        avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    },
    {
        id: 4,
        employeeName: "William Howard",
        designation: "CEO",
        email: "tony.reichert@example.com",
        dob: "29/02/1990",
        department: "Manager",
        team: "Management",
        status: "active",
        mobile: "+255 655 788 788",
        birthPlace: "Shinyanga",
        joiningDate: "29/02/2020",
        avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    },
    {
        id: 5,
        employeeName: "Kristen Copper",
        designation: "CEO",
        email: "tony.reichert@example.com",
        dob: "29/02/1990",
        department: "Manager",
        team: "Management",
        status: "active",
        mobile: "+255 655 788 788",
        birthPlace: "Shinyanga",
        joiningDate: "29/02/2020",
        avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    },
    {
        id: 6,
        employeeName: "Brian Kim",
        designation: "CEO",
        email: "tony.reichert@example.com",
        dob: "29/02/1990",
        department: "Manager",
        team: "Management",
        status: "active",
        mobile: "+255 655 788 788",
        birthPlace: "Shinyanga",
        joiningDate: "29/02/2020",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    },
    {
        id: 7,
        employeeName: "Michael Hunt",
        designation: "CEO",
        email: "tony.reichert@example.com",
        dob: "29/02/1990",
        department: "Manager",
        team: "Management",
        status: "active",
        mobile: "+255 655 788 788",
        birthPlace: "Shinyanga",
        joiningDate: "29/02/2020",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    },
    {
        id: 8,
        employeeName: "Samantha Brooks",
        designation: "CEO",
        email: "tony.reichert@example.com",
        dob: "29/02/1990",
        department: "Manager",
        team: "Management",
        status: "active",
        mobile: "+255 655 788 788",
        birthPlace: "Shinyanga",
        joiningDate: "29/02/2020",
        avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    },
    {
        id: 9,
        employeeName: "Frank Harrison",
        designation: "CEO",
        email: "tony.reichert@example.com",
        dob: "29/02/1990",
        department: "Manager",
        team: "Management",
        status: "active",
        mobile: "+255 655 788 788",
        birthPlace: "Shinyanga",
        joiningDate: "29/02/2020",
        avatar: "https://i.pravatar.cc/150?img=4",
    },
    {
        id: 10,
        employeeName: "Emma Adams",
        designation: "CEO",
        email: "tony.reichert@example.com",
        dob: "29/02/1990",
        department: "Manager",
        team: "Management",
        status: "active",
        mobile: "+255 655 788 788",
        birthPlace: "Shinyanga",
        joiningDate: "29/02/2020",
        avatar: "https://i.pravatar.cc/150?img=5",
    },
    {
        id: 11,
        employeeName: "Brandon Stevens",
        designation: "CEO",
        email: "tony.reichert@example.com",
        dob: "29/02/1990",
        department: "Manager",
        team: "Management",
        status: "active",
        mobile: "+255 655 788 788",
        birthPlace: "Shinyanga",
        joiningDate: "29/02/2020",
        avatar: "https://i.pravatar.cc/150?img=8",
    },
    {
        id: 12,
        employeeName: "Megan Richards",
        designation: "CEO",
        email: "tony.reichert@example.com",
        dob: "29/02/1990",
        department: "Manager",
        team: "Management",
        status: "active",
        mobile: "+255 655 788 788",
        birthPlace: "Shinyanga",
        joiningDate: "29/02/2020",
        avatar: "https://i.pravatar.cc/150?img=10",
    },
    {
        id: 13,
        employeeName: "Oliver Scott",
        designation: "CEO",
        email: "tony.reichert@example.com",
        dob: "29/02/1990",
        department: "Manager",
        team: "Management",
        status: "active",
        mobile: "+255 655 788 788",
        birthPlace: "Shinyanga",
        joiningDate: "29/02/2020",
        avatar: "https://i.pravatar.cc/150?img=12",
    },
    {
        id: 14,
        employeeName: "Grace Allen",
        designation: "CEO",
        email: "tony.reichert@example.com",
        dob: "29/02/1990",
        department: "Manager",
        team: "Management",
        status: "active",
        mobile: "+255 655 788 788",
        birthPlace: "Shinyanga",
        joiningDate: "29/02/2020",
        avatar: "https://i.pravatar.cc/150?img=16",
    },
    {
        id: 15,
        employeeName: "Noah Carter",
        designation: "CEO",
        email: "tony.reichert@example.com",
        dob: "29/02/1990",
        department: "Manager",
        team: "Management",
        status: "active",
        mobile: "+255 655 788 788",
        birthPlace: "Shinyanga",
        joiningDate: "29/02/2020",
        avatar: "https://i.pravatar.cc/150?img=15",
    },
    {
        id: 16,
        employeeName: "Ava Perez",
        designation: "CEO",
        email: "tony.reichert@example.com",
        dob: "29/02/1990",
        department: "Manager",
        team: "Management",
        status: "active",
        mobile: "+255 655 788 788",
        birthPlace: "Shinyanga",
        joiningDate: "29/02/2020",
        avatar: "https://i.pravatar.cc/150?img=20",
    },
    {
        id: 17,
        employeeName: "Liam Johnson",
        designation: "CEO",
        email: "tony.reichert@example.com",
        dob: "29/02/1990",
        department: "Manager",
        team: "Management",
        status: "active",
        mobile: "+255 655 788 788",
        birthPlace: "Shinyanga",
        joiningDate: "29/02/2020",
        avatar: "https://i.pravatar.cc/150?img=33",
    },
    {
        id: 18,
        employeeName: "Sophia Taylor",
        designation: "CEO",
        email: "tony.reichert@example.com",
        dob: "29/02/1990",
        department: "Manager",
        team: "Management",
        status: "active",
        mobile: "+255 655 788 788",
        birthPlace: "Shinyanga",
        joiningDate: "29/02/2020",
        avatar: "https://i.pravatar.cc/150?img=29",
    },
    {
        id: 19,
        employeeName: "Lucas Harris",
        designation: "CEO",
        email: "tony.reichert@example.com",
        dob: "29/02/1990",
        department: "Manager",
        team: "Management",
        status: "inActive",
        mobile: "+255 655 788 788",
        birthPlace: "Shinyanga",
        joiningDate: "29/02/2020",
        avatar: "https://i.pravatar.cc/150?img=50",
    },
    {
        id: 20,
        employeeName: "Mia Robinson",
        designation: "Coordinator",
        email: "tony.reichert@example.com",
        dob: "29/02/1990",
        department: "Operation",
        team: "Operation",
        status: "active",
        mobile: "+255 655 788 788",
        birthPlace: "Dallas",
        
        avatar: "https://i.pravatar.cc/150?img=45",
    },
]